### ISSUE TITLE
Alternate version

### ISSUE THREAD

**Issue by David-OConnor** [rudihorn/max31865#1]
Hi. I made an alternate version that has some misc cleanup, and borrows SPI. Should I PR it, or would you like to leave it separate? https://github.com/AnyLeaf/anyleaf-rust/blob/master/src/rtd.rs

**Comment by rudihorn** [comment]
Hi @David-OConnor, entirely up to you. If you want to PR I can look over it, pull it and resubmit to cargo. Would probably be nice not to have too many forks.

**Comment by David-OConnor** [comment]
I'll hold off unless there's more demand. This would be a pretty big breaking change to your API.
